### ISSUE TITLE
Can anyone share a working Moodle integration tutorial, please?

### ISSUE THREAD

**Issue by fishfree** [celtic-project/wordpress-lti#18] opened 2023-03-01 09:11 UTC
It's best step by step. I tried so many times, no luck:-(  Thank you VERY VERY much in advance!

**Comment by spvickers** [comment] 2023-03-01 09:36
If you are asking about how to configure this integration with Moodle, your best bet is to look at the Moodle documentation (e.g. https://docs.moodle.org/401/en/External_tool_settings).  This plugin makes WordPress act as a standard LTI tool and is configured in Moodle in the same way as any other LTI tool.  How this is done will depend upon which version of LTI you are trying to use; whilst LTI 1.0/1.1 is now out-dated, it is the simplest to configure and may be worth starting with.

**Comment by fishfree** [comment] 2023-03-06 02:08
@spvickers Thank you! I've followed the instructions from Moodle and this plugin but failed. If this plugin provide a step-by-step tutorial, that would be best!

**Comment by spvickers** [comment] 2023-03-06 10:58
Sorry, there are too many platforms to document and keep updated.  If you post a screenshot of the configuration settings for both ends then I can try to help you diagnose the cause.  How is the integration failing?  Are you using LTI 1.3?  Have you checked the log files for error messages?

**Comment by spvickers** [comment] 2023-03-25 22:48
Please re-open this issue with the requested information if you still need help.  Thanks.

**Comment by fishfree** [comment] 2023-04-12 03:29
@spvickers Would you pls reopen this issue? I attached my configuration screeshots as below:
WP (6.2) side ( Multisite enabled): 
/wp-admin/network/admin.php?page=lti_tool_options
![image](https://user-images.githubusercontent.com/1741341/231340634-db4aaa32-5817-43ae-8a96-07c468293c34.png)
![image](https://user-images.githubusercontent.com/1741341/231340682-3b4daf7c-3633-45b1-9843-89888d51cc7b.png)
Note: I use the RSA keys generated here: https://lti-ri.imsglobal.org/keygen/index A question here: I found nowhere to input or configure the generated public key.
![image](https://user-images.githubusercontent.com/1741341/231340868-f78ecd87-c316-4841-a8aa-548b6d6294c5.png)

/wp-admin/network/admin.php?page=lti_tool_add_platform&action=edit&lti=WP3-IKZRSE
![image](https://user-images.githubusercontent.com/1741341/231340249-19067496-7bd1-4fb6-8c87-fe6f97a3f821.png)
![image](https://user-images.githubusercontent.com/1741341/231340335-1d38ee1a-5994-4989-932c-975b8bd5d8b3.png)

Moodle (4.1) side: auth_lti and enrol_lti are both enabled.
![image](https://user-images.githubusercontent.com/1741341/231341120-875408d9-a85c-466d-b61b-c7e760dcca78.png)
![image](https://user-images.githubusercontent.com/1741341/231341259-c4b440dc-ba6b-4f7f-8ebc-1b9d30393236.png)

I added a lti tool activity in the Moodle, and click on it, it showed errors as below:
![image](https://user-images.githubusercontent.com/1741341/231341484-82cc1f77-97a4-46b0-8940-6c9640726fa3.png)

However, I successfully test my Moodle (as platform) with [saltire](https://saltire.lti.app/tool):
![image](https://user-images.githubusercontent.com/1741341/231346621-3a32ab10-9e94-43f3-8916-ec4e62e96f9c.png)

**Comment by spvickers** [comment] 2023-04-12 06:40
Thanks for the screenshots.  Note that public keys are normally generated automatically from the private key so do not need to be separately configured.

I can't see anything obviously wrong with your configurations.  Are you able to share the HTTP messages which are being sent when you click on the LTI link to your tool within Moodle so I can see details of the request which is being reported as being invalid?  Do the Moodle log files give any clues as to the reason for the error?

**Comment by fishfree** [comment] 2023-04-13 08:39
![image](https://user-images.githubusercontent.com/1741341/231700869-8ce813b8-2540-4234-86ed-47bc6b2f519a.png)
@spvickers Thank you. My screeshot is as above. I also checked the Moodle log, there is nothing related to lauching the tool. The cororespondent WP [debug.log](https://github.com/celtic-project/wordpress-lti/files/11220044/debug.log)
Moodle and WordPress are not in the same server, not the same timezone.

**Comment by spvickers** [comment] 2023-04-13 09:42
Thanks for the info.  I cannot see anything wrong with the authentication request being sent to the Moodle server, so I would recommend that you try to determine the reason why the script at mod/lti/auth,.php is rejecting the request.  Perhaps there is a cookie issue?

**Comment by spvickers** [comment] 2023-06-13 15:19
Assuming the issue has been resolved so closing this issue.  Please open a new one if you still need help.

**Closed as completed by spvickers** 2023-06-13 15:19 UTC
